### ISSUE TITLE
使用openapi的接口还要收费吗

### ISSUE THREAD

**Issue by yulingao** [kaixindelele/ChatPaper#100]
部署好调用后，总是报错“summary_error: You exceeded your current quota, please check your plan and billing details.”

我的账号是免费账号，难道使用openapi的接口还要收费吗

**Comment by JohnsonChang123** [comment]
是的，使用 OpenAI API 的接口需要付费。免费账号只提供有限的使用额度，一旦超过额度就会出现您所描述的错误。如果您想继续使用 OpenAI API，您可以升级到付费账号以获取更多的使用额度。--by chat gpt

**Comment by kaixindelele** [comment]
是的，大概率是你的额度已经用完了，你可以去官网查看一下
