### ISSUE TITLE
大哥能开源网站的代码吗？

### ISSUE THREAD

**Issue by EnochYe** [kaixindelele/ChatPaper#102]
想自己搭建服务网站 使用自己的api key，生成更详细的paper解读
谢谢！

**Comment by kaixindelele** [comment]
我们抱抱脸的代码是开源的啊。但目前org的代码暂时不会开源的，因为开发人员不是我一个人，后面也可能会有商业化，所以暂时不会开源。

**Comment by EnochYe** [comment]
好的 了解了
