### ISSUE TITLE
chatpaper.org端的prompt明显比仓库里的更好，请更新仓库里的prompt以支持本地用户

### ISSUE THREAD

**Issue by thusjr** [kaixindelele/ChatPaper#104]
如题。另外能更新网页端让它支持自带api更好

**Comment by WangRongsheng** [comment]
chatpaper.org里面的论文解析和仓库的解析方式不一样，prompt存在差异，暂不更新chatpaper仓库内容哦~

**Comment by isCopyman** [comment]
> 如题。另外能更新网页端让它支持自带api更好

校友，我也发现了这个问题，你有更好的prompt吗

**Comment by thusjr** [comment]
@isCopyman 无

**Comment by thusjr** [comment]
@isCopyman  看这边开发很忙也没空管开源端的prompt，我自己搓了一个😁
