### ISSUE TITLE
本地读取文件和实际不符

### ISSUE THREAD

**Issue by lyuzhenhong** [kaixindelele/ChatPaper#107]
<img width="306" alt="截屏2023-03-26 23 23 42" src="https://user-images.githubusercontent.com/67578008/227785899-ddaf67b7-c09a-4c31-87d3-8e6662006494.png">

`python chat_paper.py --pdf_path "$file_path"` 读取本地文件，输出结果和实际的文章内容不符？从图上看，是不是自动以 reinforcement learning 为关键词联网搜索了？

**Comment by kaixindelele** [comment]
如果你的文件路径如果不为空，那就应该是本地的，而不是搜索。另外目前这个基本不适合综述类文章
