### ISSUE TITLE
Bug Report 网页版生成的Basic Info不对

### ISSUE THREAD

**Issue by GarlicStem** [kaixindelele/ChatPaper#108]
![image](https://user-images.githubusercontent.com/109514687/227787181-e253349d-f3f9-43d4-ac53-d7d347dc797e.png)
如图所示，文章标题是与比特币、投资组合相关的，但检索出来的Basic Information 却不一致

**Comment by kaixindelele** [comment]
不好意思，目前不支持综述类文章
