### ISSUE TITLE
仅下载文章无总结

### ISSUE THREAD

**Issue by weirdo-onlooker** [kaixindelele/ChatPaper#110]
这是我的命令行：
 python chat_paper.py --query "spectral clustering" --filter_keys "spectral clustering" --max_results 5
运行之后下载好了文章，export文件夹中没有输出总结，且程序报错
summary_error: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f305b599460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
这是什么情况呢？

**Comment by kaixindelele** [comment]
魔法没用好
