### ISSUE TITLE
Markdown file creation failed

### ISSUE THREAD

**Issue by jingmengzhiyue** [kaixindelele/ChatPaper#113]
After inputting the PDF file, the main points of the paper were correctly input into the terminal. However, an error was reported in the code when creating the PDF file, which appears to be an error in the file name when creating the Markdown code. The error message is as follows:
OSError: [Errno 22] Invalid argument: './export\\2023-03-27-15-Bayesian Sparse Representation for Hyperspectral Image Super Resolution Naveed Akhtar, Faisal Shafait and Ajmal Mian Abstract 1. Introduction 2. Related Work 3. Problem Formulation 4. Proposed Approach 5. Experimental Evaluation 6. Discussion 7. Conclusion Acknowledgements References.md'.
The paper being tested is:
https://ieeexplore.ieee.org/document/7298986

**Comment by kaixindelele** [comment]
这是标题的解析失败了，最新版的脚本应该不会有问题的
