### ISSUE TITLE
大佬好！可以添加别的数据库的API吗？

### ISSUE THREAD

**Issue by longfuxu** [kaixindelele/ChatPaper#116]
arxiv上面很少生物医学相关的文章😭，想请问可否添加别的数据库的API，例如bioRxiv的？当然楼上也有同学提到Semantic。看到这个库https://github.com/jonatasgrosman/findpapers，可否集成，实现实时搜索加分析，不知是否可行？
另外，请教现有版本换成GPT-4 model后里面代码改动大吗？还是把模型变一下就好了？

谢谢大佬

**Comment by kaixindelele** [comment]
gpt4能用的时间还不确定，我猜国内能用到，至少得一个月以后。其他数据库以后再说
