### ISSUE TITLE
SSL连接失败

### ISSUE THREAD

**Issue by luxiancao** [kaixindelele/ChatPaper#120]
summary_error: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff67ece3970>: Failed to establish a new connection: [Errno 111] Connection refused')))

已经尝试过降级urllib

**Comment by kaixindelele** [comment]
节点的问题比较大
