### ISSUE TITLE
占个坑，我补充docker封装版本

### ISSUE THREAD

**Issue by JessyTsu1** [kaixindelele/ChatPaper#121]

**Comment by Masterlovsky** [comment]
刚想说有没有docker封板，就发现已经有大佬开了issue，支持！

**Comment by IZege** [comment]
期待一下

**Comment by kaixindelele** [comment]
其实参考一下academic那个的docker也可以做

**Comment by JessyTsu1** [comment]
> academic

我写成docker-compose

**Comment by ErictheSam** [comment]
> > 好巧，我也写了docker版
> 
> 让我来！我明天组会不管了！

lol我已经发了pr了

**Comment by JessyTsu1** [comment]
> 

没事我还能改！

**Comment by JessyTsu1** [comment]
> > > 好巧，我也写了docker版
> > 
> > 
> > 让我来！我明天组会不管了！
> 
> lol我已经发了pr了

没事我还能改！

**Comment by WangRongsheng** [comment]
good jobs!

**Comment by ErictheSam** [comment]
My pull request is at #124

**Comment by ErictheSam** [comment]
emmm原代码好像有bug，就没发布

**Comment by JessyTsu1** [comment]
我跑了一下build很慢，那个chat_ academic的build也很慢，run的时候都是报错的，我打算直接把根目录下的几个script包起来打个docker

**Comment by JessyTsu1** [comment]
finished
