### ISSUE TITLE
作者可以简单介绍一个如何处理长文档的吗？

### ISSUE THREAD

**Issue by wallon-ai** [kaixindelele/ChatPaper#122]

**Comment by hubuke** [comment]
有同样问题，在chat_paper.py/chat_summary 会报错超过4097tokens

**Comment by WangRongsheng** [comment]
请使用[chatpaper.org](https://chatpaper.org/) ，它可以很好解决长文档阅读问题

**Comment by hubuke** [comment]
感谢回复！

但是由于chatpaper.org 的pdf文件体积限制，可能无法满足需求。请问您是否有计划在开源项目中更新本功能？

超长论文案例：Quantum Information Processing and Quantum Simulation with Programmable Rydberg Atom Arrays (harvard.edu)<https://dash.harvard.edu/handle/1/37368420>
如果此例子有帮助，不胜荣幸

Buke Hu
