### ISSUE TITLE
Token 限制的問題是怎麼解決的?

### ISSUE THREAD

**Issue by davidleitw** [kaixindelele/ChatPaper#136]
您好，前几天在 GitHub 看到这个超棒的项目，前几天试用真的对读 paper 的速度很有帮助，感谢你们开发出这麽方便的工具!

对 ChatGPT 的 api 不是很熟悉，但我之前用的时候好像单次对话最多只有 4096 个 Token，有点好奇，pdf 字数超过这麽多的情况下，如何让 ChatGPT 读完这麽多资料再吐出结果，是分段餵进去之后再用总结的 Prompt 请它总结内容吗?

纯粹好奇，感谢您的回答！

**Comment by kaixindelele** [comment]
分段的，可以参考我的帖子：首先提取abs和intro的内容，然后进行集中总结，对method部分进行总结，对conclusion进行总结，总之每篇文章花费的token是他们的5倍，然后提取的信息量可能会提高个2成左右。
