### ISSUE TITLE
不能找到安装库

### ISSUE THREAD

**Issue by xhk96** [kaixindelele/ChatPaper#137]
![image](https://user-images.githubusercontent.com/108168165/229289323-f6716926-e7d3-4292-b7d7-708cd2630065.png)
![image](https://user-images.githubusercontent.com/108168165/229289367-57402134-63d9-4e7d-8dda-b36b51bb289f.png)
已安装依赖，但运行Python文件找不到库

**Comment by xhk96** [comment]
已解决，但有新问题
![image](https://user-images.githubusercontent.com/108168165/229290435-827ce039-8042-4b6e-b314-250e41309602.png)
![image](https://user-images.githubusercontent.com/108168165/229290439-082fe185-1aae-40fc-8713-bc5ab708a280.png)
找不到OpenAI的安装库

**Comment by kaixindelele** [comment]
你按照readme去安装会好些

**Comment by xhk96** [comment]
是按照readme安装的

> 你按照readme去安装会好些
