### ISSUE TITLE
chat_reviewer.py报错

### ISSUE THREAD

**Issue by just-for-stars** [kaixindelele/ChatPaper#138]
![image](https://user-images.githubusercontent.com/128011722/229297028-c23e9d76-28cb-47f8-975d-8d49667e141d.png)

**Comment by WangRongsheng** [comment]
已修正

**Comment by just-for-stars** [comment]
感谢您的帮助，但我这边出现了另外一个报错
![image](https://user-images.githubusercontent.com/128011722/229331294-0766d0a8-e976-4cbf-8d2d-4ffefde654ae.png)

**Comment by just-for-stars** [comment]
我改好了，这样就可以正常运行了
![image](https://user-images.githubusercontent.com/128011722/229331485-49228485-92d5-4b82-94d4-78515b96af9d.png)
![image](https://user-images.githubusercontent.com/128011722/229331497-20706b36-7d5f-4be4-bd96-43f23971cb04.png)
![image](https://user-images.githubusercontent.com/128011722/229331502-5ac6ad4f-5933-437b-9f3b-27520d904b4b.png)

**Comment by WangRongsheng** [comment]
good!
