### ISSUE TITLE
RuntimeError: Directory 'static/' does not exist

### ISSUE THREAD

**Issue by Bill-Gots** [kaixindelele/ChatPaper#14]
运行命令python chat_paper.py --query "chatgpt robot" --filter_keys "chat" --max_results 1 报错

**Comment by kaixindelele** [comment]
有报错截图吗？我暂时测试不了

**Comment by Bill-Gots** [comment]
![image](https://user-images.githubusercontent.com/102953387/224649842-31bbef34-0a0e-411f-8ead-bd44e2de035f.png)

**Comment by kaixindelele** [comment]
你这个python，除了我的依赖，还有安装过其他的库么？

**Comment by Bill-Gots** [comment]
哦哦现在又好了，貌似是因为有些库的版本高于requirements.txt里面的版本导致报错，我看txt里面的包我都有以为不会出现兼容性问题
