### ISSUE TITLE
http.client.IncompleteRead: IncompleteRead

### ISSUE THREAD

**Issue by KeiChiTse** [kaixindelele/ChatPaper#140]
您好，我的命令行如下：`python chat_paper.py --query "all: multimodal" --key_word "multimodal" --filter_keys "deep learning, remote sensing" --max_results 10`
显示报错：`http.client.IncompleteRead: IncompleteRead(3830 bytes read, 3097 more expected)`
但运行默认参数没有报错。

**Comment by WangRongsheng** [comment]
暂时无法复现，有问题请继续回复
