### ISSUE TITLE
Incomplete Title

### ISSUE THREAD

**Issue by pprp** [kaixindelele/ChatPaper#141]
@kaixindelele  Thank you for your great job! 

However, I found that when title of paper is incomplete after phrasing by `fitz`. 

Taking `https://arxiv.org/abs/2010.10024` as an example, the title of this paper is `Neural Architecture Performance Prediction Using Graph Neural Networks`, and only `Neural Architecture Performance Prediction` can be phrased as the title.

**Comment by kaixindelele** [comment]
是的，开源的目前解析方案是根据字体大小来判定标题的，尤其是从本地读取的时候。经常会出现只读第一行的情况。不过我们认为这些不致命，就放弃花更多精力优化了，造成困扰了，实在不好意思~
