### ISSUE TITLE
使用在线部署的方案总是报ERROR

### ISSUE THREAD

**Issue by JackiMa** [kaixindelele/ChatPaper#143]
严格按照提示使用自己的api，duplicate了huggingface的项目，但总是报这样的错误：
目前可能尝试十余次，只有一次成功解析了论文，还请指点，感谢！

`jrjl2 2023-04-03T03:26:22.228Z Traceback (most recent call last):
jrjl2 2023-04-03T03:26:22.228Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 384, in run_predict
jrjl2 2023-04-03T03:26:22.228Z     output = await app.get_blocks().process_api(
jrjl2 2023-04-03T03:26:22.228Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1032, in process_api
jrjl2 2023-04-03T03:26:22.228Z     result = await self.call_function(
jrjl2 2023-04-03T03:26:22.228Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 844, in call_function
jrjl2 2023-04-03T03:26:22.228Z     prediction = await anyio.to_thread.run_sync(
jrjl2 2023-04-03T03:26:22.228Z   File "/home/user/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
jrjl2 2023-04-03T03:26:22.228Z     return await get_asynclib().run_sync_in_worker_thread(
jrjl2 2023-04-03T03:26:22.228Z   File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
jrjl2 2023-04-03T03:26:22.228Z     return await future
jrjl2 2023-04-03T03:26:22.228Z   File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
jrjl2 2023-04-03T03:26:22.228Z     result = context.run(func, *args)
jrjl2 2023-04-03T03:26:22.228Z   File "app.py", line 778, in upload_pdf
jrjl2 2023-04-03T03:26:22.228Z     paper_list = [Paper(path=file, sl=section_list)]
jrjl2 2023-04-03T03:26:22.228Z   File "app.py", line 98, in __init__
jrjl2 2023-04-03T03:26:22.228Z     self.parse_pdf()
jrjl2 2023-04-03T03:26:22.228Z   File "app.py", line 116, in parse_pdf
jrjl2 2023-04-03T03:26:22.228Z     self.section_text_dict.update({"paper_info": self.get_paper_info()})
jrjl2 2023-04-03T03:26:22.228Z   File "app.py", line 125, in get_paper_info
jrjl2 2023-04-03T03:26:22.228Z     introduction_text = self.section_text_dict['Introduction']
jrjl2 2023-04-03T03:26:22.228Z KeyError: 'Introduction'`

`jrjl2 2023-04-03T03:27:34.267Z Traceback (most recent call last):
jrjl2 2023-04-03T03:27:34.267Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 384, in run_predict
jrjl2 2023-04-03T03:27:34.267Z     output = await app.get_blocks().process_api(
jrjl2 2023-04-03T03:27:34.267Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1032, in process_api
jrjl2 2023-04-03T03:27:34.267Z     result = await self.call_function(
jrjl2 2023-04-03T03:27:34.267Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 844, in call_function
jrjl2 2023-04-03T03:27:34.267Z     prediction = await anyio.to_thread.run_sync(
jrjl2 2023-04-03T03:27:34.267Z   File "/home/user/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
jrjl2 2023-04-03T03:27:34.267Z     return await get_asynclib().run_sync_in_worker_thread(
jrjl2 2023-04-03T03:27:34.267Z   File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
jrjl2 2023-04-03T03:27:34.267Z     return await future
jrjl2 2023-04-03T03:27:34.267Z   File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
jrjl2 2023-04-03T03:27:34.267Z     result = context.run(func, *args)
jrjl2 2023-04-03T03:27:34.267Z   File "app.py", line 785, in upload_pdf
jrjl2 2023-04-03T03:27:34.267Z     sum_info, cost = reader.summary_with_chat(
jrjl2 2023-04-03T03:27:34.267Z   File "app.py", line 589, in summary_with_chat
jrjl2 2023-04-03T03:27:34.267Z     utoken = utoken + utoken1 + utoken2 + utoken3
jrjl2 2023-04-03T03:27:34.267Z UnboundLocalError: local variable 'utoken2' referenced before assignment`

**Comment by WangRongsheng** [comment]
请注意`UnboundLocalError: local variable 'utoken2' referenced before assignment`，您可以修改`utoken2`为一个全局变量

**Comment by JackiMa** [comment]
非常感谢！似乎可用了（测试了三次失败一次）
