### ISSUE TITLE
使用最新的0ffb503版本commit，chatpaper本地运行，输出的paper不是我输入的那一篇paper

### ISSUE THREAD

**Issue by thusjr** [kaixindelele/ChatPaper#149]
使用的是python chat_paper.py --pdf_path <my paper>命令
直接就是两篇不一样的
@kaixindelele 
![image](https://user-images.githubusercontent.com/53186008/229544947-4951a792-9422-4128-b08b-c8a96fc350b8.png)

**Comment by kaixindelele** [comment]
你截图接全一点？我看看你输入的是什么？包括输出的内容

**Comment by thusjr** [comment]
窗口关掉了。但不止一次出现，你可以试图复现一下，推断是串台了，在高峰时段有概率发生。
输入就是python chat_paper.py --pdf_path “地址”
输出了完全另一篇文章的总结

**Comment by thusjr** [comment]
@kaixindelele 
你试试这篇文章A Model of the Early Visual System Based on Parallel Spike-Sequence Detection, Showing Orientation Selectivity
我重复做了三次，每次chatpaper输出结果相近，但与原文不符，题目作者都对不上

**Comment by kaixindelele** [comment]
MDPI的论文格式确实比较难识别，不过建议直接谷歌浏览器打开，然后网页翻译。
