### ISSUE TITLE
libGL error

### ISSUE THREAD

**Issue by AlongLin** [kaixindelele/ChatPaper#153]
Platform: Ubuntu 22.04 LTS
GPU: AMD Radeon HD 8750M
When I use google_scholar_spider command.

`libGL error: MESA-LOADER: failed to open crocus: /usr/lib/dri/crocus_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: crocus
libGL error: MESA-LOADER: failed to open crocus: /usr/lib/dri/crocus_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: crocus
libGL error: MESA-LOADER: failed to open swrast: /home/alo/miniconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/swrast_dri.so) (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
`
However, in the path /usr/lib/x86_64-linux-gnu/dri/, you can see crocus_dri.so and swrast_dri.so.

Thanks.

**Comment by WangRongsheng** [comment]
It may be a mistake about Linux, not chatpaper. You can reference [this](https://github.com/pybind/pybind11/discussions/3453)
