### ISSUE TITLE
请问如何在summary中 先产出英文回答再生成中文翻译

### ISSUE THREAD

**Issue by BaiyuanLiu** [kaixindelele/ChatPaper#160]
首先谢谢各位大神开发的工具。对总结文章有着超强的帮助，产出md文档也很不错。
我对代码确实不太理解，我查看了chatpaper.py文档，发现您提供的prompts例如363行 _Be sure to use {} answers (proper nouns need to be marked in English)._ （我猜测这里是控制产出中文的prompts）
我的想法是中英文结合的输出。这样也能回溯到原文进行精读。
我已经尝试了这个prompts
_"Could you kindly provide a response to my question in English followed by a Chinese translation below it?"
"请用英语回答我的问题，并在下面提供中文翻译。"_
但是并没有用，只会产出英文的回答。
希望能给我一些思路能完成中英结合输出。谢谢您的帮助！_（抱歉没找到qq群聊，就提了issues）_

**Comment by kaixindelele** [comment]
Be sure to use {} answers and original English summary as the format: "Chinese summary: xxx" \n (English summary：xxx)
也许 这样会起作用

**Comment by BaiyuanLiu** [comment]
谢谢成功了。

**Comment by BaiyuanLiu** [comment]
谢谢
