### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by WilliamOdinson** [kaixindelele/ChatPaper#163]
会一直产生 list index out of range
python chat_paper.py --query "autonomous car" --filter_keys " autonomous " --max_results 30
Key word: reinforcement learning
Query: autonomous car
Sort: SortCriterion.Relevance
all search:
……
0 Abstract 0
1 Introduction 0
start_page, end_page: 0 1
2 Related Work 1
start_page, end_page: 1 5
3 Results 5
start_page, end_page: 5 5
4 Discussion 5
start_page, end_page: 5 6
5 Method 6
start_page, end_page: 6 6
6 Conclusion 6
start_page, end_page: 6 6
7 References 6
start_page, end_page: 6 7
paper_path: ./pdf_files/autonomous car-2023-04-08-01\Model of vehicle interactions with autonomous cars and its properties.pdf
section_page_dict {'Abstract': 0, 'Introduction': 1, 'Conclusion': 16, 'References': 19}
0 Abstract 0
1 Introduction 1
start_page, end_page: 1 16
2 Conclusion 16
start_page, end_page: 16 19
3 References 19
start_page, end_page: 19 23
paper_path: ./pdf_files/autonomous car-2023-04-08-01\Motion Prediction on Self-driving Cars_ A Review.pdf
section_page_dict {'Abstract': 0, 'Introduction': 0, 'Conclusion': 6, 'References': 7}
0 Abstract 0
1 Introduction 0
start_page, end_page: 0 6
2 Conclusion 6
start_page, end_page: 6 7
3 References 7
start_page, end_page: 7 9
paper_path: ./pdf_files/autonomous car-2023-04-08-01\Are We Ready for Driver-less Vehicles_ Security vs. Privacy- A Social Perspective.pdf
section_page_dict {'Abstract': 0, 'Introduction': 0, 'Conclusion': 14, 'References': 15}
0 Abstract 0
1 Introduction 0
start_page, end_page: 0 14
2 Conclusion 14
start_page, end_page: 14 15
3 References 15
start_page, end_page: 15 17
paper_path: ./pdf_files/autonomous car-2023-04-08-01\Rain Sensing Automatic Car Wiper Using AT89C51 Microcontroller.pdf
section_page_dict {'Abstract': 0, 'Introduction': 0, 'Related Work': 0, 'Conclusion': 2, 'References': 4}
0 Abstract 0
1 Introduction 0
start_page, end_page: 0 0
2 Related Work 0
start_page, end_page: 0 2
3 Conclusion 2
start_page, end_page: 2 4
4 References 4
start_page, end_page: 4 5
paper_path: ./pdf_files/autonomous car-2023-04-08-01\ApolloCar3D_ A Large 3D Car Instance Understanding Benchmark for Autonomous Driving.pdf
section_page_dict {'Abstract': 0, 'Introduction': 0, 'Approach': 5, 'Experiments': 5, 'Method': 6, 'Results': 7, 'Methods': 7, 'Conclusion': 8, 'References': 9}
0 Abstract 0
1 Introduction 0
start_page, end_page: 0 5
2 Approach 5
start_page, end_page: 5 5
3 Experiments 5
start_page, end_page: 5 6
4 Method 6
start_page, end_page: 6 7
5 Results 7
start_page, end_page: 7 7
6 Methods 7
start_page, end_page: 7 8
7 Conclusion 8
start_page, end_page: 8 9
8 References 9
start_page, end_page: 9 13
paper_path: ./pdf_files/autonomous car-2023-04-08-01\Super-Human Performance in Gran Turismo Sport Using Deep Reinforcement Learning.pdf
section_page_dict {'Abstract': 0, 'Introduction': 0, 'Related Work': 1, 'Methodology': 1, 'Experiments': 3, 'Results': 3, 'Conclusion': 6, 'References': 7, 'Approaches': 9}
0 Abstract 0
1 Introduction 0
start_page, end_page: 0 1
2 Related Work 1
start_page, end_page: 1 1
3 Methodology 1
start_page, end_page: 1 3
4 Experiments 3
start_page, end_page: 3 3
5 Results 3
start_page, end_page: 3 6
6 Conclusion 6
start_page, end_page: 6 7
7 References 7
start_page, end_page: 7 9
8 Approaches 9
start_page, end_page: 9 12
paper_path: ./pdf_files/autonomous car-2023-04-08-01\GP22_ A Car Styling Dataset for Automotive Designers.pdf
section_page_dict {'Abstract': 0, 'Introduction': 0, 'Experiment': 2, 'Conclusion': 3, 'References': 4}
0 Abstract 0
1 Introduction 0
start_page, end_page: 0 2
2 Experiment 2
start_page, end_page: 2 3
3 Conclusion 3
start_page, end_page: 3 4
4 References 4
start_page, end_page: 4 5
summary_error: list index out of range
conclusion_error: list index out of range
summary_error: list index out of range
conclusion_error: list index out of range
summary_error: list index out of range
method_error: list index out of range
conclusion_error: list index out of range
summary_error: list index out of range

**Comment by WangRongsheng** [comment]
尝试多次运行
