### ISSUE TITLE
总结完整性疑问

### ISSUE THREAD

**Issue by xflykkk** [kaixindelele/ChatPaper#164]
目前在总结内容，包括方法总结chat_method()中都是截断内容的来进行总结，在长篇章节中如何保证总结完整性？

**Comment by kaixindelele** [comment]
233，只能勉强实现执行和效果的权衡，最佳方案是，精确提取每个章节，如果长了，就分段喂入，然后压缩出重点，然后汇总，再总结，但是这样的工程量就比较大，而且token消耗也非常恐怖。因为只用于做初筛，所以哪怕截断的信息，也勉强够用~
