### ISSUE TITLE
本地上传pdf，检索得到的结果和上传的pdf好像不太一样，不是同一篇文献

### ISSUE THREAD

**Issue by pddlzy** [kaixindelele/ChatPaper#167]
本地上传pdf，检索得到的结果和上传的pdf好像不太一样，不是同一篇文献而是用了一篇算法的文献的结果来替代这该如何解决。

**Comment by WangRongsheng** [comment]
是否尝试多次运行？

**Comment by pddlzy** [comment]
> 是否尝试多次运行？

尝试过，有时尝试几遍可以获得对的结果，有时更换了一下文件名字可以获得对的结果，不过也有出现一直出现某篇算法文章的现象。

**Comment by WangRongsheng** [comment]
建议您可以使用 chatpaper.org 帮您完成工作，它的容错率会高一些。

至于您说的问题我们也会努力排查。
