### ISSUE TITLE
可以加入检索总结SCI-HUB文章的功能吗？

### ISSUE THREAD

**Issue by Dicer-J** [kaixindelele/ChatPaper#169]
非常感谢您的工作和开源精神！
但因为跟多文献并不会上传到Arxiv，所以不知道作者可否增加从scihub检索下载并总结论文的功能

**Comment by kaixindelele** [comment]
scihub可以检索嘛？现在网页版好像可以直接贴入url，然后进行总结。原则上这个功能是打通的，现在就是不知道scihub能不能检索

**Comment by Dicer-J** [comment]
> scihub可以检索嘛？现在网页版好像可以直接贴入url，然后进行总结。原则上这个功能是打通的，现在就是不知道scihub能不能检索我看有开源方案是通过比如百度/谷歌学术检索得到DOI后再通过scihub下载，不过我没有测试。

**Comment by Dicer-J** [comment]
> > scihub可以检索嘛？现在网页版好像可以直接贴入url，然后进行总结。原则上这个功能是打通的，现在就是不知道scihub能不能检索
> 
> 我看有开源方案是通过比如百度/谷歌学术检索得到DOI后再通过scihub下载，不过我没有测试。

测试了一下，结合https://github.com/zaytoun/scihub.py与最新的google_scholar_spider.py可以直接将检索到的论文的链接通过scihub下载。
