### ISSUE TITLE
Some possible bugs

### ISSUE THREAD

**Issue by tingxueronghua** [kaixindelele/ChatPaper#17]
Thanks for your contribution! It is really convenient for researchers to quickly read the paper.

I noticed two bugs when I use your code searching the paper "Static-Dynamic Co-Teaching for Class-Incremental 3D Object Detection". I am not sure whether the bugs only exist on my computer, so maybe you can verify them first.

The first problem is that the code seems cannot recognize "-". I have no idea about why. When I search "Static-Dynamic Co-Teaching for Class-Incremental 3D Object Detection", there is no result, but when searching "Static Dynamic Co Teaching for Class Incremental 3D Object Detection" the result is correct.

The second problem is that the author list is not correct if generated by chatgpt. First time it tells me that the authors are "Wenxuan Wang, Xiangyu Chen, Shaoshuai Shi, Kaiqi Huang" and the second time it tells me that the authors are "Fangyu Liu, Zhiliang Ma, Junlan Yang, Jingyi Yu, Jinyong Jeong, Chen Feng, Rongrong Ji", which are both wrong. I found that the correct results could be gotten in the search results of arxiv. I think maybe we can trust more to arxiv's results.

**Comment by kaixindelele** [comment]
这不算bug，只是我们的代码目前还比较简陋，没对输入文本做好预处理，一切以能用就行为原则~~哈哈
