### ISSUE TITLE
收不到邮箱验证码 😢

### ISSUE THREAD

**Issue by Wonderdch** [kaixindelele/ChatPaper#170]
请问是邮件发送服务挂了吗？我和同学尝试了重庆大学的邮箱，都收不到验证码。

邮箱示例：202124131095@cqu.edu.cn

**Comment by kaixindelele** [comment]
是不是在垃圾箱？

**Comment by circlestarzero** [comment]
阿里云这边后台显示给你们学校邮箱发送成功的，但是可能被你们学校邮箱拦截了？

**Comment by Wonderdch** [comment]
> 
坏，我明天去跟学校沟通一下

**Comment by Wonderdch** [comment]
> 刚才和开发同学沟通了一下，阿里云的邮件包服务，无法给重庆大学的邮箱发邮件，非常诡异。建议可以先使用谷歌账号登录

谢谢，那我先用谷歌账号登录
