### ISSUE TITLE
请问如何正确设置gitee图床

### ISSUE THREAD

**Issue by BaiyuanLiu** [kaixindelele/ChatPaper#173]
感谢你们提供这个应用 帮助我很多。节省了很多时间和精力。
我注意到你提到可以用gitee设置图床 保存论文图片 
我按照网络上的教程设置了api，owner和repo。我大多时候读取本地pdf，我用下面的命令
python chat_paper.py --pdf_path "demo.pdf" --save_image True 
但是在输出的md文档中没有保存图片。gitee也没有变化 我觉得有可能是哪里出了问题。请问是我的命令写错了还是gitee设置的不正确？
提前感谢你们的帮助！

**Comment by kaixindelele** [comment]
图床的配置特别麻烦，我当时没保留配置教程，现在也都忘了。而且因为不能正确的提取figure位置，所以有点鸡肋，放弃这个功能吧。

**Comment by BaiyuanLiu** [comment]
好谢谢
