### ISSUE TITLE
chatPaper.org那种能够提问的效果docker能做到吗

### ISSUE THREAD

**Issue by Heresy-dd** [kaixindelele/ChatPaper#176]
如title所示，如何搭建像chatpaper.org那个网站一样的结果，能够提问和总结，flask和docker感觉还是有一点麻烦了

**Comment by kaixindelele** [comment]
网站的内容暂时还不会开源，但后期会把总结功能开源出来。因为网页可能需要走商业化，如果开源了，团队支撑不住，望谅解
