### ISSUE TITLE
自动审稿功能赶紧撤回吧

### ISSUE THREAD

**Issue by sjcfr** [kaixindelele/ChatPaper#178]
现在本来审稿人就已经稂莠不齐，各个会议中充斥着大量不负责任的审稿人。又开放这种完全自动化的工具，如何保证不被滥用？是你在开头不痛不痒讲几句类似免责声明的片汤话就能避免的吗？一旦被滥用，那么是人类主导人类的研究，还是AI主导人类的研究？这种审稿工具还可能被其他领域，如生物、医学领域的研究者滥用，尤其是质量不高的非顶级期刊会议。这将带来严重的信息污染。
这一问题需要所有研究者严肃面对。在此严肃建议撤回自动审稿功能。如非，我将三天之内以邮件形式将这一项目的存在告知贵校所有导师及今年各大顶会的程序委员会，由他们评价这一项目的合理性，以及审查贵校所有审稿人的合格性问题。

**Comment by kaixindelele** [comment]
同学您好：

首先，我们感谢您关注我们的AI辅助审稿工具，并提出您的担忧。我们非常理解您对于自动化审稿工具可能带来的潜在问题的关注。请允许我在这里澄清一些事实。

我们开发这款基于ChatGPT的辅助审稿工具的初衷是三个目的：
- 1.对arxiv最新论文进行批量总结和评审，提高科研人员的文献阅读和理解的效率。
- 2.对自己的论文进行评估，根据ChatReviewer生成的审稿意见进行查漏补缺，进一步提高自己的论文质量。
- 3.辅助审稿人进行论文审稿，利用规范化提示词，给出规范的审稿模板，以及提供一些简单的审稿意见，提高审稿效率和审稿质量。（禁止复制粘贴！）

我们认为前两个使用场景，显然是利大于弊，而您关心审稿工具可能被滥用的问题，是第三点中，确实可能存在学术伦理风险。为了降低这一风险，我们已经在工具中加入了醒目的提醒。**感谢您的提醒，我们后面会在每次输入结果中，插入其他的提示词，防止滥用。**

关于审稿人的责任问题，这是我们团队无法直接影响的。即使没有工具，如果个别审稿人不认真审稿，也可能采取敷衍了事的态度；反之，有自动化工具也不能替代，认真负责的人类专家审稿。至于审查审稿人合格性问题，应是Area Chair的职责，而非Program Chair或我们学校导师的职权。

目前，本工具只是在ChatGPT的API上进行了简单的封装。即使我们不开源，其他人也有可能开源类似工具。我们注意到您也在使用AutoGPT等工具，您也在积极地使用最新的技术。作为技术人员，在面对新技术和新工具时，我们应该充分了解其利弊并扬长避短。再者，技术的源头在于OpenAI，我们的工作相较于他们研发更加通用且强大的AGI模型来说，对人类未来的影响力实在有限。

关于您提出的告知各大顶会的程序委员会的建议，我们非常尊重您的意见。实际上，我们鼓励更多的专业人士和研究者参与评估这款工具的实际效果和潜在影响。我们相信，通过大家共同的努力和监督，我们可以更好地利用这款辅助审稿工具为学术界带来积极的影响。

后面，我们也会持续改进工具的性能，并且我们正在尝试利用OpenReview的高质量审稿数据，训练出更好的辅助审稿模型，以确保它能为更多的研究者，提供更有价值的建议。

再次感谢您的关注和建议。如果您有任何其他问题或想法，请随时与我们联系。

**Comment by sjcfr** [comment]
感谢回复。插入提示词等确实是防止滥用的积极应对。但是个人还是认为并不足够。
偷懒本身是人性的一部分。如果没有自动审稿工具的出现，或许不负责任的审稿人还能够看两眼论文，自动审稿工具的出现将使得他们连简单的阅读都不大愿意做，而强大的AI模型足以生成似是而非的评语。这将极大增加会议AC的工作量。
至于您提到我对于AutoGPT的关注，个人认为是这样，新技术需要得到应用，但是绝不能滥用。例如我们可以AutoGPT编写网页，但是绝不应该利用AutoGPT等工具开发制造流言、谣言牟利的工具。当前，自动审稿功能的出现就可以被看做是技术的一种滥用。至于您提到技术的源头在OpenAI，打个不甚恰当的比喻，弗里茨·哈伯发明了合成氨技术。这一技术也被用于合成毒气。那么难道弗里茨·哈伯要为合成毒气负责任吗？
至于为何提到通报学校导师以及会议AC/PC，诚实地讲，也是考虑到诸位开发者很可能并不愿意放弃类似自动审稿这类功能。所以，应不应该使用这类工具，还是交由更资深的研究者，例如贵校的导师来判定；在存在滥用这类工具审稿的前提下，贵校的审稿人是否合格，也交由各个会议的AC/PC来判定。

**Comment by sjcfr** [comment]
1919年弗里茨·哈伯发明的作为农药杀虫剂的齐克隆B在二战期间被纳粹德国用来作为屠杀犹太人的毒气武器。https://zh.wikipedia.org/wiki/%E5%BC%97%E9%87%8C%E8%8C%A8%C2%B7%E5%93%88%E4%BC%AF
