### ISSUE TITLE
OpenAI API - Access Terminated

### ISSUE THREAD

**Issue by bellenliu** [kaixindelele/ChatPaper#18]
请问有遇到封号情况嘛，max_result 参数设置20 + 国外云服务器动态IP配置被封了，不知道是否是一次性调用API次数过多的原因

**Comment by bellenliu** [comment]
但是后来我就按照readme的示例 max_result=1 一样被封号了，不知道大家有没有和我一样情况

**Comment by WangRongsheng** [comment]
你好，账号被封有几种情况：
（1）同一账号在短时间内被多人使用，批量调用（这里的批量指的是同一时间被频繁调用）
（2）同一ip多次进行账号注册，该ip下所有账号都会被封
（3）使用国外接码平台进行注册，OpenAI会将部分大的接码平台下注册的账号全部封禁

我们的服务仅仅是对于个人用户提供了单人单用服务。请您耐心检查自己是否出现以上违规现象，我们也将继续关注此问题，谢谢
