### ISSUE TITLE
Report an example mistake

### ISSUE THREAD

**Issue by zzzjl2021** [kaixindelele/ChatPaper#195]
![image](https://user-images.githubusercontent.com/80235159/234167835-abcb7a6e-f243-41e4-b73c-d9d36b787cd2.png)
### It should be the 'au' as the list provided below.
![image](https://user-images.githubusercontent.com/80235159/234168004-91f17e6a-e2a6-47fb-b5b1-903d975f50fe.png)

**Comment by kaixindelele** [comment]
多谢提醒，我修改一下~
