### ISSUE TITLE
关于生成MD总结缺少Part.7 Methods的问题

### ISSUE THREAD

**Issue by MarsyCantStopCoding** [kaixindelele/ChatPaper#203]
您好，请问为什么生成的文档中有些论文会包含第七部分，也就是论文中使用的方法，而其他论文没有。生成文档使用的命令基本相同，只有关键词的差别。下面是示例

不包含第七部分的生成案例：
## Paper:5

1. Title: Eth2Vec: Learning Contract-Wide Code Representations for Vulnerability Detection on Ethereum Smart Contracts (以太坊智能合约漏洞检测中基于ConWin的代码表示学习)

2. Authors: Nami Ashizawa, Naoto Yanai, Jason Paul Cruz, Shingo Okamura

3. Affiliation: Nami Ashizawa, Naoto Yanai, and Jason Paul Cruz are affiliated with Osaka University; Shingo Okamura is affiliated with the National Institute of Technology, Nara College. (Nami Ashizawa，Naoto Yanai，Jason Paul Cruz：大阪大学， Shingo Okamura：奈良高等専門学校)

4. Keywords: Ethereum, smart contract, vulnerability detection, machine learning, static analysis (以太坊，智能合约，漏洞检测，机器学习，静态分析)

5. Urls: Paper: http://arxiv.org/abs/2101.02377v2 Github: None

6. Summary:
- (1): 近年来，以太坊上的智能合约漏洞不断高发，目前存在的安全分析工具在代码重写方面准确度下降。本文提出一种名为Eth2Vec的机器学习静态分析工具，能够在以太坊智能合约的代码重写方面保持稳健性。 
- (2): 过去的方法如符号执行受限，安全分析准确度有限。本文提出的机器学习方法消除了对手动制定的特征依赖，通过神经网络进行自动学习，避免了手动制定特征时的不确定性问题。本方法能够识别以太坊虚拟机字节码中的漏洞，并且在重写代码方面有稳定的表现。
- (3): 本文提出了一种基于自然语言处理的神经网络方法，能够自动学习EVM字节码和汇编代码的特征。通过比较目标EVM字节码和已经学习过的EVM字节码之间的代码相似性，能够检测以太坊智能合约的漏洞。 
- (4): 本文提出的方法在Etherscan等开放数据库验证中表现出色，准确性，召回率和F1分数均优于现有方法。 此外，Eth2Vec即使在重写代码的情况下也能够检测漏洞。

8. Conclusion: 

- (1): 本文的意义在于提出了一种新的方法——基于自然语言处理的神经网络方法，能够自动学习以太坊智能合约的漏洞特征，增强了基于机器学习的静态分析工具的表现。 该方法能够在智能合约代码重写情况下保持稳健性，有效地检测以太坊智能合约中的漏洞。

- (2): 创新点： 本文创新性地提出了一种基于自然语言处理的神经网络方法，能够自动学习以太坊智能合约的漏洞特征。性能：该方法在以太坊开放数据库验证中表现优异，准确性，召回率和F1分数均优于现有方法；在代码重写情况下，该方法仍然能够保持良好的检测效果。工作量：本文的研究方法需要进行大量的数据预处理工作，涉及到自然语言处理和神经网络等多个领域的专业知识。

包含第七部分的生成案例：

## Paper:9

1. Title: Targeting the Weakest Link: Social Engineering Attacks in Ethereum Smart Contracts(以太坊智能合约中的社会工程学攻击研究)

2. Authors: Nikolay Ivanov, Jianzhi Lou, Ting Chen, Jin Li, Qiben Yan

3. Affiliation: 密歇根州立大学(Michigan State University)

4. Keywords: Ethereum, Smart contracts, Attacks, Security, Social engineering.

5. Urls: Paper link: http://arxiv.org/abs/2105.00132v2 , Github: None.

6. Summary: 
- (1): 本研究探讨了以太坊智能合约中社交工程攻击的可能性。因为以太坊智能合约持有数十亿美元的Ether加密货币和ERC-20令牌，安全始终受到严格的监视。但当攻击代码漏洞的机会变少时，攻击者开始转向社会工程攻击，以影响人类，通常是系统中最弱的环节。本文研究了新的社交工程攻击，探讨了在以太坊中存在的两种攻击类型，即地址操纵和同形异义词攻击，并开发了六种零日社交工程攻击。
- (2): 本文从人员中心角度出发，对以往的智能合约安全风险进行了分析，发现现有的智能合约安全研究没有考虑人的因素。因此，本文提出了一个人员中心的方法，即社交工程攻击，以克服人的认知偏见，越过系统的安全边界，从而实现攻击。
- (3): 本文开发了六种针对以太坊智能合约的零日社交工程攻击，并通过在五个市值超过29亿美元的智能合约的源代码中集成攻击模式的实验，验证了它们的有效性。此外，作者在制作程序时，采用潜藏于智能合约中的利用入口，使攻击代码在测试阶段保持休眠状态，只有在最终生产部署时才会触发攻击。
- (4): 本文的贡献包括：提出两类新的以太坊社会工程攻击类型；开发了六种零日攻击模式；分析了85,656个开源的智能合约，并发现其中1,027个可以用于作者提出的社交工程攻击；证明了这些攻击对智能合约系统构成了巨大的威胁。
7. Methods: 

- (1): 本研究开发了一个混合自动化筛选工具，用于从给定的智能合约集中选择潜在的候选合约，进而进行手动分析，以检测社交工程攻击。使用这种混合方法，我们可以过滤掉超过95.4％的智能合约，然后手动检查可疑智能合约，并将它们分类为三个类别：非易感、语法匹配和语义易感。最后，我们向七个领先的智能合约安全公司的安全专家及更多人提供了我们的发现。

- (2): 本文从人员中心角度出发，对以往的智能合约安全风险进行了分析，发现现有的智能合约安全研究没有考虑人的因素。因此，本文提出了一个人员中心的方法，即社交工程攻击，以克服人的认知偏见，越过系统的安全边界，从而实现攻击。

- (3): 本文开发了一个基于Python的智能合约扫描工具，并使用ethereum.utils和Web3.py来实现它。工具预处理源代码，去除非Solidity智能合约、擦除所有注释并丢弃先前处理过的智能合约的副本。接下来，我们将源代码输入到一组签名探测器中，根据签名生成社交工程攻击检测规则。最后，我们使用在线调查的方式将研究结果与许多安全公司的安全专家分享。本研究未使用传统的智能合约漏洞扫描工具，因为这些工具假定智能合约是攻击目标。而唯一公开的符合本文攻击模式的工具是HoneyBadger，但这也不是所有情况。因此，本文开发了一种特定的智能合约扫描工具来实现这一目标。

- (4): 本文分析并开发了两种类型的以太坊社交工程攻击：地址操纵和同型异义词攻击，并通过在五个市值超过29亿美元的智能合约的源代码中集成攻击模式的实验，验证了它们的有效性。此外，本文对85,656个开源的智能合约进行了手动分类分析，并发现了1,027个可以用于作者提出的社交工程攻击。

8. Conclusion: 

- (1): 本篇文章的意义在于挖掘了以太坊智能合约中社交工程攻击的潜在威胁，并提出了多种零日攻击模式，为智能合约安全研究提供了新的视角和思路。

- (2): 创新点：本文从人员中心角度出发，提出了社交工程攻击这一与传统漏洞不同的攻击方式，对智能合约安全研究提出了新的挑战。性能：文章开发的智能合约扫描工具能够有效地检测潜在的候选合约，并找出可以用于作者提出的攻击的合约。但文章在开发攻击模式的实验中，只选取了五个具有较高市值的智能合约，实验结果并不能代表所有智能合约的安全性。工作量：本文通过混合自动化筛选工具和手动分类分析的方式，对85,656个开源的智能合约进行了分析，展示了对智能合约系统的广泛关注和深入研究。

请问如何输入命令才会保证ChatGPT调用API后生成第七部分，麻烦您回答一下，非常感谢！

**Comment by kaixindelele** [comment]
因为有些文章的方法部分不是method章节名，这个需要人工添加修改才行。但操作起来比较麻烦，所以我一直没加～
