### ISSUE TITLE
使用chat_arxiv.py不出结果

### ISSUE THREAD

**Issue by gxandys** [kaixindelele/ChatPaper#204]
我运行命令：
python chat_arxiv.py --query "land use efficiency" --key_word "land use efficiency" --max_results 10
后，出现如下信息：
Key word: land use efficiency
Query: land use efficiency
Sort: None
----------------------------------------
summary time: 3.0216119289398193
然后就没有然后了。。。
py文件中已加入了os.environ["http_proxy"]语句，chat_paper.py这个程序是正常的。
不知道是哪里出了问题。

**Comment by kaixindelele** [comment]
你得设定时间，day，可能最近几天没有相关的文章，就没有结果
