### ISSUE TITLE
huggingface app.py/chat_sumary 到了 4.mark the keywords of this article 之后无法获取结果

### ISSUE THREAD

**Issue by wangweifeng2018** [kaixindelele/ChatPaper#205]
huggingface app.py 的结果与官网[https://chatpaper.org/] chatPaper 结果不一致，
huggingface app.py/chat_sumary  到了 4.mark the keywords of this article 就无法正常获取结果了，
作者可以给出点关于prompt的修改建议么，非常感谢🙏

**huggingface 结果**：
1. Title: Mapping allele with resolved carrier status of Reciprocal Translocations Robertsonian Translocations (用于确定互换转位和罗伯逊转位携带者状态的等位基因映射)
2. Authors: Xu K, Zhang J, Li Y, et al.
3. 中国科学院生物物理研究所 (Institute of Biophysics, Chinese Academy of Sciences)
**<这里的4,5,6点没有展示>**
7. Methods:
(1): 本研究采用了基于PCR技术的等位基因映射方法，通过PCR扩增样本DNA中与互换转位或罗伯逊转位相关的位点，进而确定携带者的等位基因。
(2): 样本的DNA提取采用了标准的酚/氯仿法，PCR扩增反应中使用了特异性引物，PCR产物经过电泳分离并进行测序验证。
(3): 本研究共收集了200名互换转位或罗伯逊转位携带者的样本，对其进行了等位基因映射分析，最终得出了这些携带者的等位基因分布情况。
8. Conclusion:
(1): 本研究的意义在于采用了基于PCR技术的等位基因映射方法，能够准确地确定互换转位或罗伯逊转位的携带者状态，为相关疾病的筛查和诊断提供了重要参考。
(2): 创新点：本研究采用了基于PCR技术的等位基因映射方法，能够准确地确定互换转位或罗伯逊转位的携带者状态，具有较高的准确性和可靠性。性能：本研究共收集了200名携带者的样本，并对其进行了等位基因映射分析，最终得出了这些携带者的等位基因分布情况，结果具有较高的可信度和科学性。工作量：本研究的样本量较大，需要进行大量的实验操作和数据分析，但研究者们成功地完成了这项工作，为相关领域的研究提供了重要数据支持

**chatpaper.org结果：**
Basic Information:
Title: Mapping allele with resolved carrier status of Robertsonian and reciprocal translocation in human preimplantation embryos 人早期胚胎中Robertsonian和互换易位的等位基因与携带状态的映射
Authors: Jiawei Xu, Zhen Zhang, Wenbin Niu, Qingling Yang, Guidong Yao, Senlin Shi, Haixia Jin, Wenyan Song, Lei Chen, Xiangyang Zhang, Yihong Guo, Yingchun Su, Linli Hu, Jun Zhao, Yile Zhang, Fangli Dong, Yumei Gao, Wenhui Li, Shiping Bo, Mintao Hu, Jun Ren, Lei Huang, Sijia Lu, X. Sunney Xie, and Yingpu Sun
Affiliation: The First Affiliated Hospital of Zhengzhou University, Zhengzhou, Henan, 450052, China
Keywords: reciprocal translocation (RecT), Robertsonian translocations (RobT), chromosomal abnormality, preimplantation genetic testing (PGD), Comprehensive Chromosome Screening (CCS), next-generation sequencing (NGS), Mapping allele with resolved carrier status (MaReCs)
URLs: https://www.pnas.org/content/114/40/E8695, GitHub: None
摘要：
a. 本文的研究背景:
研究载体状态的解析: MaReCs
b. 过去的方法、问题和动机:
CCS无法确认胚胎是否携带易位染色体。
c. 本文提出的研究方法:
NGS技术的MaReCs，对胚胎进行染色体平衡和易位筛查，以明确载体状态，
d. 实验方法和结果:
MaReCs成功筛查了来自16名患者的108个胚胎，并在羊水和活产中得到证实。
背景：
a. 主题和特点:
染色体易位及其导致的不孕和出生缺陷。
b. 历史发展：
过去的PGD技术不能有效地识别携带易位染色体的胚胎。
c. 过去的方法：
CCS（全面染色体筛查）
d. 过去的研究缺点：
不能确定胚胎是否可用
e. 当前需要解决的问题：
识别不携带易位染色体的胚胎，以降低传递易位染色体纯合体风险。
方法：
a. 本研究的理论基础：
MaReCs技术的基本原理
b. 该文的技术路线（一步一步）：
由有易位染色体的父母所遗传的某一异常等位基因确定信息型单核苷酸多态性（SNP）序列
通过逻辑减法将SNP的连锁类型与健康的父母所遗传的SNP连锁类型相减，以确定携带易位染色体和正常等位基因的连锁型
...
c. 结果分析：
确定了携带交换染色体的患者的健康胚胎，降低了其出生缺陷和易位纯合体风险
结论：
a. 工作的重要性：
有效降低了患者出生缺陷和易位纯合体风险
b. 创新、性能和工作量：
MaReCs在携带易位染色体的患者中识别出不携带易位染色体的胚胎，在精确检测基因突变性和精简工作流程方面具有创新性
c. 研究结论（列出关键结果）：
MaReCs可成功筛查出羊水和活产中的易位染色体，这对于携带易位染色体的家庭和未来胚胎选择极其重要。
本研究采用NGS技术，利用MaReCs方法，对胚胎进行染色体平衡和易位筛查。MaReCs技术的特点是在基因突变性检查过程中，同步检测易位染色体引起的胚胎染色体变化。该研究成功筛选了来自16名患者的108个胚胎，并通过实验结果证明MaReCs技术在筛查出不携带易位染色体的健康胚胎方面准确性高、有效性强。通过采集患者体液或胎儿羊水中的样本来验证该技术的准确性，发现检测结果与传统的PGD结果一致。 这一研究为携带易位染色体的家庭提供了新的筛查技术，为解决易位染色体问题提供了新的思路，该研究揭示了利用MaReCs方法了解胚胎载体状态的机制，为今后的PGD流程提供了更多技术支持。

**Comment by WangRongsheng** [comment]
good jobs!
