### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by paketecuento** [kaixindelele/ChatPaper#21]
I would like to thank you for your dedication and effort in keeping this project up and running. 

I wanted to propose a new feature that would allow users to download PDF files directly from Sci-Hub. As you know, Sci-Hub provides free access to millions of academic articles. Adding this feature would greatly enhance the usability of your software .

**Comment by 1kaiser** [comment]
and google colab version too ! 🙏🏻

**Comment by kaixindelele** [comment]
sci-hub的文档下载可能不是很方便，可能需要爬虫手动爬取。但医学和生物的预印本可以考虑一下这个库：https://pypi.org/project/paperscraper
至于colab的话，自己配置也很方便。但是我的测试结果是，colab和openai的通信有时候会出问题~

**Comment by paketecuento** [comment]
Please, check this library for sci-hub: https://pypi.org/project/scidownl/

It is working very good and provide metadata information
