### ISSUE TITLE
网页端对话模式会开源吗？

### ISSUE THREAD

**Issue by xieqk** [kaixindelele/ChatPaper#223]
你好，我发现网页端是支持针对每一个文献进行对话的，界面中左边显示pdf原文，右边为对话框，支持对话询问。感觉这个功能非常实用，请问这一部分以后会开源吗？

**Comment by WangRongsheng** [comment]
这一部分的工作或许您可以参考：https://github.com/WangRongsheng/Knowledge-Base-LLMs-QA
