### ISSUE TITLE
网页版，开始用着还挺好，后来就error了

### ISSUE THREAD

**Issue by fengqiii** [kaixindelele/ChatPaper#23]
是因为什么？
<img width="502" alt="截屏2023-03-14 13 45 41" src="https://user-images.githubusercontent.com/75001434/224907764-7e1f0c9f-27f7-42cc-a984-8b388a3d1227.png">

**Comment by fengqiii** [comment]
<img width="487" alt="截屏2023-03-14 13 47 33" src="https://user-images.githubusercontent.com/75001434/224907853-d3f18925-3e92-4597-b9b8-c8edc030a4d0.png">

**Comment by fengqiii** [comment]
出现两行是奇怪的地方。

**Comment by WangRongsheng** [comment]
- 第一行用于输出本次论文解析使用的token
- 第二行用于输出对全文的总结内容

我们已经注意到相关的使用错误，可以尝试多次运行来解读您的论文，谢谢

**Comment by fengqiii** [comment]
> * 第一行用于输出本次论文解析使用的token
> * 第二行用于输出对全文的总结内容
> 
> 我们已经注意到相关的使用错误，可以尝试多次运行来解读您的论文，谢谢

我记得开始用的时候只有一行呀。尝试了挺多遍了还是失败。刚刚盯着看了，queue是14个，结束后突然就error了。

**Comment by DSXiangLi** [comment]
同上我尝试了多次依旧是error

**Comment by WangRongsheng** [comment]
> 同上我尝试了多次依旧是error

请耐心等待

**Comment by tianxuanzhizi** [comment]
求自建Huggingface网页的教程

**Comment by WangRongsheng** [comment]
> 求自建Huggingface网页的教程

Huggingface允许用户自己写入静态、gradio、streamlit等书写的界面进行可视化使用。具体页面编写请搜索参考：gradio使用文档、streamlit使用文档等
