### ISSUE TITLE
为什么我在自己电脑配置了，用自己的API还有配额超出的问题？

### ISSUE THREAD

**Issue by qq799602401** [kaixindelele/ChatPaper#236]
summary_error: You exceeded your current quota, please check your plan and billing details.

**Comment by qq799602401** [comment]
summary_error: You exceeded your current quota, please check your plan and billing details.
method_error: You exceeded your current quota, please check your plan and billing details.
conclusion_error: You exceeded your current quota, please check your plan and billing details.
summary_error: You exceeded your current quota, please check your plan and billing details.

**Comment by kaixindelele** [comment]
因为你的api额度过期了~
