### ISSUE TITLE
手机端适配问题

### ISSUE THREAD

**Issue by cyclekiller** [kaixindelele/ChatPaper#238]
网页版在手机上体验很差，希望改进
建议推出chatpaper QQ机器人，来解决手机端的问题。这样更方便。
![Screenshot_20230608_175634](https://github.com/kaixindelele/ChatPaper/assets/48796459/e34ae941-80f2-49cd-b4f8-cd635aa2e24b)
![Screenshot_20230608_175642](https://github.com/kaixindelele/ChatPaper/assets/48796459/05d3a0ff-3052-43a2-86b0-e77efd1cad28)
![Screenshot_20230608_175652](https://github.com/kaixindelele/ChatPaper/assets/48796459/e18a43e5-adff-4144-8d2f-ae08b17660aa)
![Screenshot_20230608_175704](https://github.com/kaixindelele/ChatPaper/assets/48796459/59a81b26-a253-428b-bc4a-89b9182ab9e1)

**Comment by Jaseon-Q** [comment]
感谢关注！月底就会上线手机端。网站同步持续迭代。
