### ISSUE TITLE
非计算机专业的报告，总结出完全不相干的内容。。。

### ISSUE THREAD

**Issue by gxandys** [kaixindelele/ChatPaper#241]
![图片](https://github.com/kaixindelele/ChatPaper/assets/52304029/925cdc53-1fec-4fd3-a3a9-738f931c2989)
是需要调试哪些部分代码么？如果可以的话麻烦给个思路。我不是计算机专业的，想有个本专业也能用的版本。

**Comment by Jaseon-Q** [comment]
Hi 感谢指出！这不是算法和引擎问题，这应该是由于我们在优化网站架构、做迁移时候的小bug，总结和文章有个别没对应。我们已经修复这个问题。
