### ISSUE TITLE
summary_error: InvalidRequestError.__init__() missing 1 required positional argument: 'param' <class 'TypeError'> chat_paper.py 464 conclusion_error: InvalidRequestError.__init__() missing 1 required positional argument: 'param' <class 'TypeError'> chat_paper.py 537

### ISSUE THREAD

**Issue by ThomasXIONG151215** [kaixindelele/ChatPaper#252]
今天下载的库，输入的是“python chat_paper.py --pdf_path "C:\Users\Administrator\Downloads\植物工厂流场与能源"”，文件夹里是从zotero导出的文库文件夹，文件夹里的files里面每个pdf又都在独立的子文件夹不知道是不是因为这个的原因

**Comment by ThomasXIONG151215** [comment]
![屏幕截图 2023-07-16 174242](https://github.com/kaixindelele/ChatPaper/assets/60814001/bf9dee3e-2294-4111-852e-2d54f20c470d)

**Comment by ThomasXIONG151215** [comment]
问题如图，是出现在程序清点论文数目之后，清点出了91篇论文，export里出现了空的51个markdown

**Comment by kaixindelele** [comment]
应该是子文件夹好像不行

**Comment by ThomasXIONG151215** [comment]
好嘞
