### ISSUE TITLE
导入软件依赖失败。使用该模块需要额外依赖，安装方法pip install --upgrade pdfminer beautifulsoup4。

### ISSUE THREAD

**Issue by Dylandtt** [kaixindelele/ChatPaper#258]
函数插件功能？
下载arxiv论文并翻译摘要，函数插件作者[binary-husky]。正在提取摘要并下载PDF文档……

解析项目: https://arxiv.org/abs/2307.01848
导入软件依赖失败。使用该模块需要额外依赖，安装方法pip install --upgrade pdfminer beautifulsoup4。

**Comment by kaixindelele** [comment]
不要点击底下那个，点上面那个arxiv翻译
