### ISSUE TITLE
ChatPaper2Xmind - 从pdf生成Xmind脑图笔记草稿

### ISSUE THREAD

**Issue by MasterYip** [kaixindelele/ChatPaper#261]
大佬好~

ChatPaper为我平时阅读文献提供了很大帮助。受到ChatPaper项目的启发，这几天简单实现了一个**将论文通过ChatGPT转换成Xmind思维导图**的工具，同时加入了**图片和公式提取的功能**，方便Chatpaper文献筛查后的深入阅读和笔记记录。

希望这个工具能够为ChatPaper贡献一份力量~

以下是项目链接：
[ChatPaper2Xmind](https://github.com/MasterYip/ChatPaper2Xmind)

效果大致如下所示：
![publish](https://github.com/kaixindelele/ChatPaper/assets/73632805/b583313c-807e-479f-b2f0-9dc53baa9b40)

**Comment by kaixindelele** [comment]
感谢关注和开源，非常优雅的功能！
另外我也正在修正PDF的解析包，朋友也推荐我使用PDFfigures 2.0!
