### ISSUE TITLE
运行报错：summary_error: You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by BGB007** [kaixindelele/ChatPaper#263]
按照bilibili的教程安装好了环境和各种依赖包，在分析本地PDF文件（WiFi7的草案）时报错：
0 Draft P802.11be_D4.0.pdf
summary_error: You exceeded your current quota, please check your plan and billing details.
<class 'openai.error.RateLimitError'> chat_paper.py 464
method_error: You exceeded your current quota, please check your plan and billing details.
<class 'openai.error.RateLimitError'> chat_paper.py 500
conclusion_error: You exceeded your current quota, please check your plan and billing details.
<class 'openai.error.RateLimitError'> chat_paper.py 537
summary time: 88.59644436836243

请问这个问题如何解决？
我用的是chatgpt3.5版本（免费版）

**Comment by kaixindelele** [comment]
应该是你的账号注册时间超过3个月了，免费额度过期了
