### ISSUE TITLE
运行Chat_translate.py代码，连接报错怎么解决呢？

### ISSUE THREAD

**Issue by dzysunshine** [kaixindelele/ChatPaper#264]
parse_pdf_to_dict(path: HTTPConnectionPool(host='localhost', port=8070): Max retries exceeded with url: /api/processFulltextDocument (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f443973da90>: Failed to establish a new connection: [Errno 111] Connection refused'))
<class 'requests.exceptions.ConnectionError'> chat_translate.py 31
Traceback (most recent call last):
  File "/students/julyedu_522454/ChatPaper/chat_translate.py", line 228, in <module>
    main(root_path, pdf_path, key, task)
  File "/students/julyedu_522454/ChatPaper/chat_translate.py", line 163, in main
    paper_pdf = parse_pdf(pdf_path)    
  File "/students/julyedu_522454/ChatPaper/chat_translate.py", line 41, in parse_pdf
    return pdf
UnboundLocalError: local variable 'pdf' referenced before assignment

**Comment by kaixindelele** [comment]
这是你的scipdf没有启动，或者没有安装好

**Comment by dzysunshine** [comment]
好的，解决了，感谢！

**Comment by kmeiMagma** [comment]
请问楼上怎么解决的 之前可以已经正常使用了 最近run又报错了 一模一样的报错 请问你的解决方案是什么呢

**Comment by dzysunshine** [comment]
在运行这个代码之前，需要先启动scipdf服务，也就是bash serve_grobid.sh




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kaixindelele/ChatPaper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月19日(星期四) 上午6:39
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [kaixindelele/ChatPaper] 运行Chat_translate.py代码，连接报错怎么解决呢？ (Issue #264)





 
请问楼上怎么解决的 之前可以已经正常使用了 最近run又报错了 一模一样的报错 请问你的解决方案是什么呢
