### ISSUE TITLE
为什么gpt4出来，chatpaper就死了

### ISSUE THREAD

**Issue by c782464295** [kaixindelele/ChatPaper#29]
我觉得还是可以做出不错的效果的。

**Comment by yingxiongyanjin** [comment]
怎么就死了？

**Comment by c782464295** [comment]
> 怎么就死了？

GPT4出来后，ChatPaper已经死了！
作者自己写的

**Comment by WangRongsheng** [comment]
GPT4是一个比ChatGPT更强大的存在，它已经学会了读全文这种东西，所以我们在继续努力去改善我们的ChatPaper，主要有了GPT4的api，我们也会尽快接入的！！（这不是玩笑）

**Comment by kaixindelele** [comment]
只是昨天晚上看到GPT4.0的强大上下文能力，让我感到了技术的强大。
冷静来看，我们的方案，即使gpt4.0的接口发布，我们的ChatPaper则应该具有更强的性能才是，这并不冲突。抱歉，之前的评述，让大家困扰了~
