### ISSUE TITLE
chat_paper.xy报错

### ISSUE THREAD

**Issue by c-d-e** [kaixindelele/ChatPaper#294]
summary_error: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
这个是我账号有问题吗还是设置的问题？跟着教程走下来好像前面都没毛病。。

**Comment by kaixindelele** [comment]
是你的api额度没了，或者是过期了，可以进后台看看
