### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by Walshyu** [kaixindelele/ChatPaper#295]

**Comment by Liltomato1998** [comment]
![微信图片_20240401202653](https://github.com/kaixindelele/ChatPaper/assets/74699281/8e5467dd-d517-4ebf-b7aa-566fb5cccfac)

**Comment by Walshyu** [comment]
<img width="1268" alt="屏幕截图 2024-04-24 192538" src="https://github.com/kaixindelele/ChatPaper/assets/74699281/81b48af6-7f00-4571-8b9d-7000b5ae3898">

**Comment by kaixindelele** [comment]
你的api过期了。

**Comment by Walshyu** [comment]
是自己创建的api吗？我是刚创建的 但是跑脚本的时候显示api过期 我该怎么 选择合适的api呢

**Comment by kaixindelele** [comment]
过期的是你的账号，注册超过3个月了，或者说是最近注册的（因为最近注册的号没有api调用额度）。
所以你最好去选择一些贩子卖的中转api（别问我，我不推荐，然后3.5的价格不要超过1美元额度0.6元都可以接受。）
