### ISSUE TITLE
文件名过长错误：本地部署，正确上传、读取并处理后，在输出md文件的时候把summary内容整个命名为md文件名，导致系统报错

### ISSUE THREAD

**Issue by beankin** [kaixindelele/ChatPaper#30]
测试其他pdf文件均正常，目前只碰到这一个文件有问题。文件名为：“Integrated_bioprocess_for_conversion_of_gaseoussubstrates_to_liquids.pdf”，下载链接为：“https://www.pnas.org/doi/10.1073/pnas.1516867113”

报错内容如下：

Traceback (most recent call last):
  File "/home/cyril/git/ChatPaper/chat_paper.py", line 467, in <module>
    main(args=args)
  File "/home/cyril/git/ChatPaper/chat_paper.py", line 435, in main
    reader1.summary_with_chat(paper_list=paper_list)
  File "/home/cyril/git/ChatPaper/chat_paper.py", line 243, in summary_with_chat
    self.export_to_markdown("\n".join(htmls), file_name=file_name, mode=mode)
  File "/home/cyril/git/ChatPaper/chat_paper.py", line 395, in export_to_markdown
    with open(file_name, mode, encoding="utf-8") as f:
OSError: [Errno 36] File name too long: './export/2023-03-15-07-Integrated bioprocess for conversion of gaseous Peng Hu oncerns over diminishing oil reserves and climate-changing renewable liquid fuels (1). One promising direction has been the We have shown previously that acetate in excess of 30 g_L can be produced from mixtures of CO and CO_H Significance Results limitation during growth on H M. thermoacetica content of 61%, which is the highest reported to date on acetate. Carbon fluxes were calculated for this run. sumes acetic acid and converts the carbon to CO system of Fig. 1 was assembled and operated as shown in Table 1. threefold higher than the first stage when CO_CO The time courses of cell growth and lipids production in the aerobic bioreactor are presented in Fig. 10. Lipid titer was 18 g_L Discussion conversion process. First, we used the acetogen Second, this work highlights a novel gas composition switch strategy as an important part of the process required for achieving Third, as summarized in Table 2, the numbers of merit obtained for the integrated system are lower than those achieved for the efficiency (from hydrogen to lipid and yeast) of the integrated Fourth, there is significant potential for reduction of CO emissions in our system compared with the single-stage systems. The main limitation in biodiesel (the primary renewable al- ternative to diesel) production is feedstock availability and cost Materials and Methods.md'

**Comment by kaixindelele** [comment]
这个应该是title的字符串解析错了，导致了这么长的标题名，然后文件名是靠标题来的。所以会报错。如果少量的话，忽略吧，pdf的格式千奇百怪，我也很难全部考虑到，太复杂了
