### ISSUE TITLE
是否考虑支持 chatPDF 类似的交互提问与回答功能？

### ISSUE THREAD

**Issue by Dounm** [kaixindelele/ChatPaper#31]
目前来看，ChatPaper 仅支持对某个  paper 进行 summarize，但这对于充分理解一个 paper来说并不足够。

所以是否考虑类似 https://www.chatpdf.com/ 一样，可以把 paper 作为一个 bot，进行提问与对话呢

**Comment by kaixindelele** [comment]
暂时不考虑对话，因为我们觉得chatpaper只擅长用来初筛，如果确定某篇文章对自己有价值，要真正的理解，是需要人去通篇阅读的，而不是简单的靠ai解读，这种理解太浅，对人的认知来说并不是好事儿。况且，如果真的需要，直接使用他们就好了~
