### ISSUE TITLE
论文标题获取方法有问题

### ISSUE THREAD

**Issue by jasonzysun** [kaixindelele/ChatPaper#33]
我在本地环境尝试了使用，通过分析多篇文件进行了测试，有个明显的问题是识别出来的标题等基本信息就不对，经过分析，发现当标题存在多行时，只有第一行的内容会完整的出现在分析结果了，后面可能就会跟上一串完全不同的看似相关的内容（人工智能开始进行经典的胡编乱造了）类似的问题导致标题、作者信息等基本情况出现问题，猜测时识别pdf文件时没有考虑这点（没有分析源码验证这部分），进而引起后面的文章分析的不准确。

**Comment by kaixindelele** [comment]
是的，这段内容的解析是有问题的，但是我目前没有耐心再看那段的逻辑了，代码写的太难看了，哈哈，标题不是那么的重要，凑活用吧
