### ISSUE TITLE
本地pdf总结： 运行chat_paper.py，报错

### ISSUE THREAD

**Issue by wf395962475** [kaixindelele/ChatPaper#39]
python3 chat_paper.py --pdf_path "demo.pdf"

Key word: reinforcement learning
Query: all: ChatGPT robot
Sort: SortCriterion.Relevance
max_font_sizes [9.962599754333496, 9.962599754333496, 9.962599754333496, 9.962599754333496, 9.962599754333496, 10.958900451660156, 10.958900451660156, 23.91029930114746, 23.91029930114746, 29.88789939880371]
Traceback (most recent call last):
  File "/Users/fan/work/gitlab/ChatPaper/chat_paper.py", line 468, in <module>
    main(args=args)
  File "/Users/fan/work/gitlab/ChatPaper/chat_paper.py", line 426, in main
    paper_list.append(Paper(path=args.pdf_path))
  File "/Users/fan/work/gitlab/ChatPaper/get_paper_from_pdf.py", line 16, in __init__
    self.title = self.get_title()
  File "/Users/fan/work/gitlab/ChatPaper/get_paper_from_pdf.py", line 160, in get_title
    self.title_page = page_index
NameError: name 'page_index' is not defined

**Comment by wtyuyuyu** [comment]
注释掉get_paper_from_pdf.py第160行，可以运行出demo的结果

**Comment by WangRongsheng** [comment]
> python3 chat_paper.py --pdf_path "demo.pdf"
> 
> Key word: reinforcement learning Query: all: ChatGPT robot Sort: SortCriterion.Relevance max_font_sizes [9.962599754333496, 9.962599754333496, 9.962599754333496, 9.962599754333496, 9.962599754333496, 10.958900451660156, 10.958900451660156, 23.91029930114746, 23.91029930114746, 29.88789939880371] Traceback (most recent call last): File "/Users/fan/work/gitlab/ChatPaper/chat_paper.py", line 468, in main(args=args) File "/Users/fan/work/gitlab/ChatPaper/chat_paper.py", line 426, in main paper_list.append(Paper(path=args.pdf_path)) File "/Users/fan/work/gitlab/ChatPaper/get_paper_from_pdf.py", line 16, in **init** self.title = self.get_title() File "/Users/fan/work/gitlab/ChatPaper/get_paper_from_pdf.py", line 160, in get_title self.title_page = page_index NameError: name 'page_index' is not defined

已修复！

**Comment by WangRongsheng** [comment]
> +1 same problem

已修复！
