### ISSUE TITLE
关于非arxiv论文的一些问题

### ISSUE THREAD

**Issue by WangRongsheng** [kaixindelele/ChatPaper#4]
感谢您的项目，我想请问：

（1）请问是否支持本地非arxiv论文解读？
（2）请问支持的论文的最大页数是多少？
（3）对于某些论文的某些标题可能不是标准的，该如何处理？（如正常arxiv论文会有一个Experimental，但是如果现在有一篇论文它的标题则是Experimental results and analysis，是否我们需要去在代码中增加入"Experimental results and analysis"这个标题词）

谢谢~

**Comment by kaixindelele** [comment]
(1)本地非Arxiv论文是可以的，目前只支持单一文件，不能支持文件夹整体解读（这个也好加）
(2)支持的论文阅读页数无所谓，因为我的方案取巧了，主要信息提取是看摘要和简介，方法部分是截取少部分，以及总结。因此其他的部分，我的方案会忽略。但一般来说摘要和简介已经够了。
(3)章节不标准比较麻烦，我目前的方案比较固定，拿不到关键词，就会被忽略。需要增加新关键词，或者用其他方案来提取。

**Comment by WangRongsheng** [comment]
![vD8vX.png](https://i.328888.xyz/2023/03/12/vD8vX.png)

基于您的项目，我们在自己的内部实现了一个可视化版本，关于章节，我们采用自输入方法。

**Comment by kaixindelele** [comment]
哇塞，这个是我也正在做的，还得是可视化后，受众更广，好多小白用户，不会配置python~
你们这个UI设计的好看！
