### ISSUE TITLE
将静态资源内置于项目内

### ISSUE THREAD

**Issue by d4renk** [kaixindelele/ChatPaper#61]
我搭建了一个公益站点
但国内大部分地区加载不了cloudflare
且加载fonts.googleapis.com异常缓慢
希望将静态资源内置于项目内

**Comment by kaixindelele** [comment]
什么意思？我们团队明天尝试上线我们自己的网页版了，由于成本的考虑，应该限制到每人每天3篇，然后可能需要自己配置api或者购买服务才能继续使用，到时候欢迎大家尝试
