### ISSUE TITLE
[小白的疑惑] Windows上能跑但是内置的WSL跑不起来？

### ISSUE THREAD

**Issue by Mvrjustid** [kaixindelele/ChatPaper#62]
读取本地pdf这块儿，在windows自带的git bash（或者其他命令行）上能够跑出完整的结果，但是进入到WSL之后只能到下面读出三篇文章这里，GPT似乎就不返回结果了。

------------------paper_num: 3------------------
0 ./pdf_files/ReadMore/2206.03687.pdf
1 ./pdf_files/ReadMore/4102_polyloss_a_polynomial_expansio.pdf
2 ./pdf_files/ReadMore/BenchmarkNLU4FewShotLearning.pdf

WSL到这里就不运行了...但同一台机器的windows上面可以完整跑出结果。

小白第一次尝试WSL...也许是WSL上linux没有配置好？

**Comment by Mvrjustid** [comment]
另试了一下找在线论文，WSL也是卡在调用GPT那一步：

Key word: reinforcement learning
Query: chatgpt robot
Sort: SortCriterion.Relevance
all search:
0 A Human-Centered Safe Robot Reinforcement Learning Framework with Interactive Behaviors 2023-03-02 12:41:01+00:00
1 Can ChatGPT Understand Too? A Comparative Study on ChatGPT and Fine-tuned BERT 2023-03-02 14:33:12+00:00
2 Seeing ChatGPT Through Students' Eyes: An Analysis of TikTok Data 2023-03-09 15:46:54+00:00
filter_keys: chatgpt robot
筛选后剩下的论文数量：
filter_results: 1
filter_papers:
0 A Human-Centered Safe Robot Reinforcement Learning Framework with Interactive Behaviors 2023-03-02 12:41:01+00:00
All_paper: 1
paper_path: ./pdf_files/chatgpt robot-2023-03-19-23/A Human-Centered Safe Robot Reinforcement Learning Framework with Interactive Behaviors.pdf
section_page_dict {'Abstract': 0, 'Introduction': 0, 'Conclusion': 10, 'References': 11}
0 Abstract 0
1 Introduction 0
start_page, end_page: 0 10
2 Conclusion 10
start_page, end_page: 10 11
3 References 11
start_page, end_page: 11 20

就没下文了。有点奇怪哈，期待解答~~~

**Comment by WangRongsheng** [comment]
您好,

一般情况下，ChatPaper只依赖于Python环境，所有系统，包括`WSL` 都是支持的。鉴于您的错误，我们建议您可以这样做：

1. 继续尝试多次运行相同服务；
2. 换用篇幅内容较短的paper进行服务使用；
3. 等待我们全新的ChatPaper上线，全新的ChatPaper将会以更高效、合理、简单的方式运行，并且具有更高的容错率。

谢谢您的支持和理解~

**Comment by kaixindelele** [comment]
我听别人的反馈是，wsl和openai的通信有问题，建议直接用Windows

**Comment by Mvrjustid** [comment]
> > 读取本地pdf这块儿，在windows自带的git bash（或者其他命令行）上能够跑出完整的结果，但是进入到WSL之后只能到下面读出三篇文章这里，GPT似乎就不返回结果了。
> > ------------------paper_num: 3------------------ 0 ./pdf_files/ReadMore/2206.03687.pdf 1 ./pdf_files/ReadMore/4102_polyloss_a_polynomial_expansio.pdf 2 ./pdf_files/ReadMore/BenchmarkNLU4FewShotLearning.pdf
> > WSL到这里就不运行了...但同一台机器的windows上面可以完整跑出结果。
> > 小白第一次尝试WSL...也许是WSL上linux没有配置好？
> 
> wsl没法直接连接windows代理 在wsl里部署一个代理后 添加Linux代理 临时添加环境变量
> 
> ```
> export http_proxy=http://127.0.0.1:7890/
> export https_proxy=http://127.0.0.1:7890
> export no_proxy=127.0.0.1,localhost
> ```
> 
> 永久添加环境变量得写进用户变量里
> 
> ```
> 编辑 .bashrc 文件 vim ~/.bashrc
> 文件末尾添加：export PATH="
> source ~/.bashrc
> ```
> 
> 检查环境变量是否添加 `env | grep -E 'http_proxy|https_proxy`

虽然又出了别的错误，但是你这个提醒很好！
这个工具还是决定去原生环境用吧。
谢谢

**Comment by liuxilai** [comment]
> > 读取本地pdf这块儿，在windows自带的git bash（或者其他命令行）上能够跑出完整的结果，但是进入到WSL之后只能到下面读出三篇文章这里，GPT似乎就不返回结果了。
> > ------------------paper_num: 3------------------ 0 ./pdf_files/ReadMore/2206.03687.pdf 1 ./pdf_files/ReadMore/4102_polyloss_a_polynomial_expansio.pdf 2 ./pdf_files/ReadMore/BenchmarkNLU4FewShotLearning.pdf
> > WSL到这里就不运行了...但同一台机器的windows上面可以完整跑出结果。
> > 小白第一次尝试WSL...也许是WSL上linux没有配置好？
> 
> wsl没法直接连接windows代理 在wsl里部署一个代理后 添加Linux代理 临时添加环境变量
> 
> ```
> export http_proxy=http://127.0.0.1:7890
> export https_proxy=http://127.0.0.1:7890
> export no_proxy=127.0.0.1,localhost
> ```
> 
> 永久添加环境变量得写进用户变量里
> 
> ```
> 编辑 .bashrc 文件 vim ~/.bashrc
> 文件末尾添加
> export http_proxy=http://127.0.0.1:7890
> export https_proxy=http://127.0.0.1:7890
> :wq保存退出
> 载入变量
> source ~/.bashrc
> ```
> 
> 检查环境变量是否添加 `env | grep -E 'http_proxy|https_proxy`

是可以的，

```
export HTTP_PROXY="http://`grep -oP '(?<=nameserver ).+' /etc/resolv.conf`:7890"
 export HTTPS_PROXY="http://`grep -oP '(?<=nameserver ).+' /etc/resolv.conf`:7890"
```
通过这个可以获取ip地址，去走windows本地的clash端口
