### ISSUE TITLE
能不能把本地批量阅读的结果export到一个md文件中

### ISSUE THREAD

**Issue by QYQSDTC** [kaixindelele/ChatPaper#76]
现在是每个pdf都单独的有一个md文件总结，能不能合并为一个文件输出

**Comment by QYQSDTC** [comment]
就是我每天的arxiv爬虫会根据我的关键字每天爬取pdf然后存到一个目录，每天大概有个10-20篇，然后再用chatpaper去批量的读，我想最后就只用读一个集合的总结文件就行了，现在是每个单独pdf都会有一个md

**Comment by kaixindelele** [comment]
如果老哥自己会用python爬虫的话，其实你是可以自己修改那部分代码的。修改一下路径就好了。
