### ISSUE TITLE
a bug happened for several times when I just use: python chat_paper.py --pdf_path ...

### ISSUE THREAD

**Issue by tednb** [kaixindelele/ChatPaper#78]
D:\ChatPaper-main\biorxiv\2023.03.20\26.pdf
Processing 26.pdf...
Key word: reinforcement learning
Query: all: ChatGPT robot
Sort: SortCriterion.Relevance
max_font_sizes [20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0]
section_page_dict {'Abstract': 1}
0 Abstract 1
start_page, end_page: 1 18
------------------paper_num: 1------------------
0 26.pdf
Traceback (most recent call last):
  File "D:\ChatPaper-main\chat_paper.py", line 478, in <module>
    main(args=args)
    ^^^^^^^^^^^^^^^
  File "D:\ChatPaper-main\chat_paper.py", line 446, in main
    reader1.summary_with_chat(paper_list=paper_list)
  File "D:\ChatPaper-main\chat_paper.py", line 187, in summary_with_chat
    htmls.append(chat_summary_text)
                 ^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'chat_summary_text' where it is not associated with a value

**Comment by kaixindelele** [comment]
2333,不好意思，我可能新更新了一个bug!我立刻检查一下

**Comment by kaixindelele** [comment]
你俩用的都是最新版吗？

**Comment by WayneMao** [comment]
是的，刚刚clone的代码

**Comment by WayneMao** [comment]
是的，刚刚clone的代码

看着像这里出错：
```
response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=messages,
        )
```

**Comment by kaixindelele** [comment]
如果是这里的话，就几种报错，网络问题，api被封，token超过4096.导致最终拿不到文本信息，我用一个粗糙的方案解决报错吧

**Comment by WayneMao** [comment]
嗯嗯，确实是账户的问题，简单加个报错就行
