### ISSUE TITLE
Error！

### ISSUE THREAD

**Issue by ZCyueternal** [kaixindelele/ChatPaper#80]
本地PDF，运行了一段时间后报错。
python .\chat_paper.py --pdf_path '.\localpdf\2022-CVPR-Learning_To_Imagine_Diversify_Memory_for_Incremental_Learning_Using_Unlabeled_Data.pdf'

Traceback (most recent call last):
  File "D:\STUDY\code\ChatPaper\chat_paper.py", line 478, in <module>
    main(args=args)
  File "D:\STUDY\code\ChatPaper\chat_paper.py", line 446, in main
    reader1.summary_with_chat(paper_list=paper_list)
  File "D:\STUDY\code\ChatPaper\chat_paper.py", line 187, in summary_with_chat
    htmls.append(chat_summary_text)
UnboundLocalError: local variable 'chat_summary_text' referenced before assignment

**Comment by ZedRover** [comment]
感觉大概率是api_key有问题，建议在chat_paper.py:178 行添加                print("chat_summary_error:", e)查看报错信息
![image](https://user-images.githubusercontent.com/29392414/226544495-97ce55e1-542d-43d3-8fb2-488c48212337.png)

**Comment by dhdgves** [comment]
把你的api_key用双引号括起来就行了，像这样：

```ini
[OpenAI]
introductioon = the api key does not ''
OPENAI_API_KEYS = "sk-xxxxxxxxxxx"
```
