### ISSUE TITLE
A bug happened-- ModuleNotFoundError: No module named 'arxiv'

### ISSUE THREAD

**Issue by HeathBrothers** [kaixindelele/ChatPaper#82]
(base) jingxiao@ec2-34-215-129-247 ChatPaper-main % pip install arxiv
Requirement already satisfied: arxiv in /Users/jingxiao/opt/anaconda3/lib/python3.9/site-packages (1.4.3)
Requirement already satisfied: feedparser in /Users/jingxiao/opt/anaconda3/lib/python3.9/site-packages (from arxiv) (6.0.10)
Requirement already satisfied: sgmllib3k in /Users/jingxiao/opt/anaconda3/lib/python3.9/site-packages (from feedparser->arxiv) (1.0.0)
(base) jingxiao@ec2-34-215-129-247 ChatPaper-main % python chat_paper.py --pdf_path "demo.pdf"
Traceback (most recent call last):
  File "chat_paper.py", line 5, in <module>
    import arxiv
ModuleNotFoundError: No module named 'arxiv'

vscode run enviroment:  /Users/jingxiao/opt/anaconda3/lib/python3.9

**Comment by kaixindelele** [comment]
你这个我是十分的纳闷，你激活了新的虚拟环境么？

**Comment by HeathBrothers** [comment]
嗯啦，我新建并激活了虚拟环境，但是很奇怪，重新安装了pip install -r requirements.txt之后，仍然报错。
ModuleNotFoundError: No module named ‘arxiv'
即使我单独pip install arxiv之后,仍然报错：No module named ‘arxiv'
myenv-chatpaper) ***@***.*** ChatPaper-main % pip install arxiv

Requirement already satisfied: arxiv in /Users/jingxiao/opt/anaconda3/envs/myenv-chatpaper/lib/python3.9/site-packages (1.4.3)
Requirement already satisfied: feedparser in /Users/jingxiao/opt/anaconda3/envs/myenv-chatpaper/lib/python3.9/site-packages (from arxiv) (6.0.10)
Requirement already satisfied: sgmllib3k in /Users/jingxiao/opt/anaconda3/envs/myenv-chatpaper/lib/python3.9/site-packages (from feedparser->arxiv) (1.0.0)




| |
man_in_the_mirror
|
|
***@***.***
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 03/22/2023 15:48 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [kaixindelele/ChatPaper] A bug happened-- ModuleNotFoundError: No module named 'arxiv' (Issue #82) |

你这个我是十分的纳闷，你激活了新的虚拟环境么？

**Comment by kaixindelele** [comment]
感觉是python的环境路径问题，这个我一时半会儿帮助不了了~

**Comment by weibinqiu** [comment]
try to use python3 instead of python?

**Comment by HeathBrothers** [comment]
Thank you very much for your suggestion! 
I followed your advice and replaced "python" with "python3" in the command, and it worked like a charm.
 The error message (No module named 'arxiv') did not appear again. 
I really appreciate your help and support!



| |
man_in_the_mirror
|
|
***@***.***
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 03/27/2023 12:45 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [kaixindelele/ChatPaper] A bug happened-- ModuleNotFoundError: No module named 'arxiv' (Issue #82) |

try to use python3 instead of python?
