### ISSUE TITLE
您好，本地pdf报错

### ISSUE THREAD

**Issue by tiangongdao2077** [kaixindelele/ChatPaper#87]
Key word: reinforcement learning
Query: all: ChatGPT robot
Sort: SortCriterion.Relevance
max_font_sizes [9.962599754333496, 9.962599754333496, 11.9552001953125, 11.9552001953125, 11.9552001953125, 11.9552001953125, 11.9552001953125, 11.9552001953125, 14.346199989318848, 20.0]
section_page_dict {'Abstract': 0, 'Related Work': 0, 'Approach': 6, 'Approaches': 3, 'Experiments': 7, 'Conclusion': 9, 'References': 9}
0 Abstract 0
start_page, end_page: 0 0
1 Related Work 0
start_page, end_page: 0 6
2 Approach 6
start_page, end_page: 6 3
3 Approaches 3
start_page, end_page: 3 7
4 Experiments 7
start_page, end_page: 7 9
5 Conclusion 9
start_page, end_page: 9 9
6 References 9
start_page, end_page: 9 15
Traceback (most recent call last):
  File "chat_paper.py", line 470, in <module>
    main(args=args)    
  File "chat_paper.py", line 428, in main
    paper_list.append(Paper(path=args.pdf_path))            
  File "H:\du\ChatPaper-main\get_paper_from_pdf.py", line 17, in __init__
    self.parse_pdf()            
  File "H:\du\ChatPaper-main\get_paper_from_pdf.py", line 33, in parse_pdf
    self.section_text_dict.update({"paper_info": self.get_paper_info()})
  File "H:\du\ChatPaper-main\get_paper_from_pdf.py", line 42, in get_paper_info
    introduction_text = self.section_text_dict['Introduction']
KeyError: 'Introduction'
读本地单个pdf报错

**Comment by kaixindelele** [comment]
更新一下代码就好了
