### ISSUE TITLE
argparse解析参数的错误/bug for argparse

### ISSUE THREAD

**Issue by Rphone** [kaixindelele/ChatPaper#9]
在命令行执行python文件`chat_paper.py` 输入参数`--sort arxiv.SortCriterion.LastUpdatedDate`会报错

```
AttributeError: 'str' object has no attribute 'value'
```

经过检查发现在`chat_paper.py`文件中解析`--sort`参数的代码是

```
parser.add_argument("--sort", default=arxiv.SortCriterion.Relevance, help="another is arxiv.SortCriterion.LastUpdatedDate")
```

可能是由于`parser.add_argument`方法中没有指定`type`参数,因此python默认将`arxiv.SortCriterion.LastUpdatedDate`作为`str`类型解析,则与预期不符,由于`arxiv.SortCriterion`是枚举类型,因此应该先指定`type`参数

```
parser.add_argument("--sort", default=arxiv.SortCriterion.Relevance,type=arxiv.SortCriterion, help="another is arxiv.SortCriterion.LastUpdatedDate")
```

并在命令行传入枚举类型的值`--sort lastUpdatedDate` 才能正常运行
请问这是一个bug么?

**Comment by Rphone** [comment]
如有必要我可以提交PR修复这个小问题

**Comment by kaixindelele** [comment]
> 在命令行执行python文件`chat_paper.py` 输入参数`--sort arxiv.SortCriterion.LastUpdatedDate`会报错
> 
> ```
> AttributeError: 'str' object has no attribute 'value'
> ```
> 
> 经过检查发现在`chat_paper.py`文件中解析`--sort`参数的代码是
> 
> ```
> parser.add_argument("--sort", default=arxiv.SortCriterion.Relevance, help="another is arxiv.SortCriterion.LastUpdatedDate")
> ```
> 
> 可能是由于`parser.add_argument`方法中没有指定`type`参数,因此python默认将`arxiv.SortCriterion.LastUpdatedDate`作为`str`类型解析,则与预期不符,由于`arxiv.SortCriterion`是枚举类型,因此应该先指定`type`参数
> 
> ```
> parser.add_argument("--sort", default=arxiv.SortCriterion.Relevance,type=arxiv.SortCriterion, help="another is arxiv.SortCriterion.LastUpdatedDate")
> ```
> 
> 并在命令行传入枚举类型的值`--sort lastUpdatedDate` 才能正常运行 请问这是一个bug么?

多谢提醒，我马上修改一下，我在args里面还是传字符串，然后加上判断筛选出真正的sort，会好一些

**Comment by Rphone** [comment]
> > 在命令行执行python文件`chat_paper.py` 输入参数`--sort arxiv.SortCriterion.LastUpdatedDate`会报错
> > ```
> > AttributeError: 'str' object has no attribute 'value'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 经过检查发现在`chat_paper.py`文件中解析`--sort`参数的代码是
> > ```
> > parser.add_argument("--sort", default=arxiv.SortCriterion.Relevance, help="another is arxiv.SortCriterion.LastUpdatedDate")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可能是由于`parser.add_argument`方法中没有指定`type`参数,因此python默认将`arxiv.SortCriterion.LastUpdatedDate`作为`str`类型解析,则与预期不符,由于`arxiv.SortCriterion`是枚举类型,因此应该先指定`type`参数
> > ```
> > parser.add_argument("--sort", default=arxiv.SortCriterion.Relevance,type=arxiv.SortCriterion, help="another is arxiv.SortCriterion.LastUpdatedDate")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 并在命令行传入枚举类型的值`--sort lastUpdatedDate` 才能正常运行 请问这是一个bug么?
> 
> 多谢提醒，我马上修改一下，我在args里面还是传字符串，然后加上判断筛选出真正的sort，会好一些

好的,感谢您的辛勤劳动
