### ISSUE TITLE
sometimes needed reduce the length of the messages.

### ISSUE THREAD

**Issue by thusjr** [kaixindelele/ChatPaper#91]
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 4114 tokens. Please reduce the length of the messages.
使用的论文题目：https://www.frontiersin.org/articles/10.3389/fninf.2022.884245/pdf @kaixindelele

**Comment by kaixindelele** [comment]
是的，这种稍微的长度差别，真的很难避免。尤其是中英文混杂的，你看其实就差几十个token，比较难解决，只能建议换一篇文章了。
