### ISSUE TITLE
空输出

### ISSUE THREAD

**Issue by Chetni** [kaixindelele/ChatPaper#94]
![image](https://user-images.githubusercontent.com/128563962/227222595-2767acc5-6588-4610-8f1a-f7cb63a57280.png)
想请教一下大佬们是怎么回事，换了macos和Windows虚拟机，都是m1芯片，python版本也试了最新的和3.9版本，项目也更新到了新版本，都是空输出，网页版也会error

**Comment by kaixindelele** [comment]
最最新版本，应该有error输出的。

**Comment by kaixindelele** [comment]
加个马赛克，终端和ini的文本截图发一下

**Comment by Chetni** [comment]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/128563962/227229620-8646a694-fcd5-4ca2-862a-955f7aac322f.png">

<img width="937" alt="image" src="https://user-images.githubusercontent.com/128563962/227229418-4f7028df-3467-406b-bcdd-df38ac1c26eb.png">

**Comment by kaixindelele** [comment]
你的格式搞错了，看我的readme，正确的是[sk-xxxx,]
