### ISSUE TITLE
运行后结果为空，求解

### ISSUE THREAD

**Issue by estuday** [kaixindelele/ChatPaper#95]
![H%4)9Z4%SNV9X}S8HT$8H@S](https://user-images.githubusercontent.com/45581281/227405254-43b4f686-9dbd-4bf3-a362-846dda86a756.png)
![image](https://user-images.githubusercontent.com/45581281/227405322-d0799695-5fed-4749-a165-4d9d6ab91c4c.png)
![image](https://user-images.githubusercontent.com/45581281/227405414-002d4360-1c43-4ff4-a9f0-581bb6bbfeca.png)

**Comment by Chetni** [comment]
多了逗号和空格

**Comment by estuday** [comment]
> 多了逗号和空格

去掉空格和逗号后依旧是空的。。请问怎么办

**Comment by Chetni** [comment]
看一下issue94在 2023年3月24日，14:00，estuday ***@***.***> 写道：﻿

多了逗号和空格

去掉空格和逗号后依旧是空的。。请问怎么办

**Comment by estuday** [comment]
> 看一下issue94在 2023年3月24日，14:00，estuday ***@***.***> 写道：﻿ 多了逗号和空格 去掉空格和逗号后依旧是空的。。请问怎么办 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

![image](https://user-images.githubusercontent.com/45581281/227453905-9443b95d-0480-4950-9b7c-5e25f4cfb4a9.png)
![image](https://user-images.githubusercontent.com/45581281/227453962-e2f8bc01-3cab-433a-87ee-c103d9b800be.png)
都试过了，都是为空

**Comment by Chetni** [comment]
不知道了

**Comment by kaixindelele** [comment]
最新的脚本会有报错的，不会无输出

**Comment by Kirikirito** [comment]
我也是类似的问题：
![1679907965562](https://user-images.githubusercontent.com/44674527/227895507-33d3ff40-7cf1-4d18-87eb-8abc1bc26a89.png)
感觉程序卡死在了某个地方

**Comment by estuday** [comment]
> 我也是类似的问题： ![1679907965562](https://user-images.githubusercontent.com/44674527/227895507-33d3ff40-7cf1-4d18-87eb-8abc1bc26a89.png) 感觉程序卡死在了某个地方

下载最新的有报错，我已经解决了，在代码里加代理代理ip和端口就行
