### ISSUE TITLE
读取某些本地PDF输出的内容有些异常

### ISSUE THREAD

**Issue by Chetni** [kaixindelele/ChatPaper#97]
<img width="1743" alt="截屏2023-03-24 11 44 04" src="https://user-images.githubusercontent.com/128563962/227419356-9644dab3-8a45-4806-ab36-8470d935f96e.png">
<img width="1743" alt="截屏2023-03-24 11 43 52" src="https://user-images.githubusercontent.com/128563962/227419369-34d69b53-b187-4a51-a967-b5ecf288d02a.png">
绿色标签为准确读取的文件；橙色标签读取的内容不符，但方向类似。
选中的md文件为完全不是同一领域的输出，找不到他读取的PDF文件是哪一个，之后我会逐个尝试，在此issue下追加。

**Comment by Chetni** [comment]
https://ottodesu.lanzoum.com/iLO0G0qy1kah

**Comment by LiXiHan26** [comment]
我也有这种情况，基本上都是综述类的文章才会出现这样的情况，不知道是不是一些综述类的文章一般不带有Introduciton、Method之类的大标题标签所以内容会出现变化

**Comment by kaixindelele** [comment]
对，这个总结模板不适合综述类文章！只适合方法性的文章！
